---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - /bin/cp -R app assets bin config migrations public src templates tests translations var .cpanel.yml .htaccess importmap.php .env composer.json composer.lock symfony.lock vendor $DEPLOYPATH