<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOh8TrmF\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOh8TrmF/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOh8TrmF.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOh8TrmF\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOh8TrmF\App_KernelProdContainer([
    'container.build_hash' => 'Oh8TrmF',
    'container.build_id' => '4af972ab',
    'container.build_time' => 1713742500,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOh8TrmF');
