<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'app_login_check' => [[], ['_controller' => 'App\\Controller\\LoginController::loginCheck'], [], [['text', '/login-check']], [], [], []],
    'app_post' => [[], ['_controller' => 'App\\Controller\\PostController::index'], [], [['text', '/lista']], [], [], []],
    'app_post_deletepost' => [['id'], ['id' => null, '_controller' => 'App\\Controller\\PostController::deletePost'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post/delete']], [], [], []],
    'app_post_getposts' => [[], ['_controller' => 'App\\Controller\\PostController::getPosts'], [], [['text', '/posts']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\LoginController::login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\LoginController::logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\LoginController::loginCheck' => [[], ['_controller' => 'App\\Controller\\LoginController::loginCheck'], [], [['text', '/login-check']], [], [], []],
    'App\Controller\PostController::index' => [[], ['_controller' => 'App\\Controller\\PostController::index'], [], [['text', '/lista']], [], [], []],
    'App\Controller\PostController::deletePost' => [['id'], ['id' => null, '_controller' => 'App\\Controller\\PostController::deletePost'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post/delete']], [], [], []],
    'App\Controller\PostController::getPosts' => [[], ['_controller' => 'App\\Controller\\PostController::getPosts'], [], [['text', '/posts']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
];
