<?php

namespace ContainerOh8TrmF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetPostsCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\GetPostsCommand' shared autowired service.
     *
     * @return \App\Command\GetPostsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\GetPostsCommand'] = $instance = new \App\Command\GetPostsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:get-posts');
        $instance->setDescription('Get posts');

        return $instance;
    }
}
